In [62]:

try:
    import sklearn
except ModuleNotFoundError:
    import subprocess, sys, importlib
    subprocess.check_call([sys.executable, "-m", "pip", "install", "scikit-learn"])
    sklearn = importlib.import_module("sklearn")
import pickle
import warnings

In [63]:
%pip install sklearn


  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.


  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-

In [64]:
import sklearn
import numpy as np
import pandas as pd
import matplotlib_inline as plt
import pickle
import warnings


In [65]:
warnings.filterwarnings("ignore")

In [66]:
df = pd.read_csv(r"C:\Users\sonik\Desktop\python lerning\ML\1) Regression\2) Multiple Linear Regression\Practical Codes\50_Startups.csv")

In [67]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [68]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [69]:
x = df.drop(columns='Profit')
y = df['Profit']

In [70]:
x.head()

R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [71]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [72]:
df['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [73]:
x = pd.get_dummies(data =x, columns=['State'],drop_first=True)
x.head()

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0  165349.20       136897.80        471784.10          False            True
1  162597.70       151377.59        443898.53          False           False
2  153441.51       101145.55        407934.54           True           False
3  144372.41       118671.85        383199.62          False            True
4  142107.34        91391.77        366168.42           True           False

In [74]:
from sklearn.preprocessing import RobustScaler

sc = RobustScaler()

x[['R&D Spend', 'Administration', 'Marketing Spend']] = sc.fit_transform(
    x[['R&D Spend', 'Administration', 'Marketing Spend']]
)

x.head()


R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   1.496732        0.345355         1.522416          False            True
1   1.452113        0.697565         1.358546          False           False
2   1.303634       -0.524290         1.147203           True           False
3   1.156567       -0.097977         1.001848          False            True
4   1.119836       -0.761543         0.901764           True           False

In [77]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=102)


In [79]:
x_train

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
12   0.337504        0.112392         0.218155           True           False
17   0.350370        0.544322         0.410522          False            True
30  -0.179297       -0.171693        -0.714496           True           False
42  -0.801249       -0.644839        -0.380299          False           False
5    0.953936       -0.556662         0.882330          False            True
22   0.015300        0.002018         0.532430           True           False
6    0.998345        0.595921        -0.499500          False           False
11   0.447908       -0.751841         0.217597          False           False
46  -1.163285       -0.167438         0.495967           True           False
36  -0.719797        0.105966        -0.068105           True           False
40  -0.718328       -0.101037        -0.234594          False           False
38  -0.856568       -1.380444        -0.161317          False            True
48  -1.175827       -1.725964        -1.250030          False            True
35  -0.438440       -0.915864        -0.042303          False            True
27  -0.015300        0.125629         0.825459          False            True
28  -0.113507        1.458133        -0.555730           True           False
25  -0.135996        0.409945        -0.439291          False           False
39  -0.559341       -0.966102        -0.221644          False           False
16   0.080466       -0.026811         0.303403          False           False
49  -1.184617       -0.139037        -0.984570          False           False
32  -0.156361        0.158589        -0.979209          False           False
3    1.156567       -0.097977         1.001848          False            True
18   0.303213       -0.207340         0.483069           True           False
4    1.119836       -0.761543         0.901764           True           False
7    0.928334        0.555328         0.653236           True           False
15   0.672530       -0.002018         0.288302          False            True
44  -0.824976        0.780961        -1.083520          False           False
45  -1.168397        0.035349        -1.238841          False            True
8    0.770134        0.632895         0.581170          False            True
9    0.815416       -0.341041         0.542199          False           False
43  -0.933171        0.113898        -1.041213          False            True
2    1.303634       -0.524290         1.147203           True           False
47  -1.184617        0.309577        -1.250030          False           False
14   0.760416        0.823317         0.257372           True           False
0    1.496732        0.345355         1.522416          False            True

In [81]:
y_train

12    141585.52
17    125370.37
30     99937.59
42     71498.49
5     156991.12
22    110352.25
6     156122.51
11    144259.40
46     49490.75
36     90708.19
40     78239.91
38     81229.06
48     35673.41
35     96479.51
27    105008.31
28    103282.38
25    107404.34
39     81005.76
16    126992.93
49     14681.40
32     97427.84
3     182901.99
18    124266.90
4     166187.94
7     155752.60
15    129917.04
44     65200.33
45     64926.08
8     152211.77
9     149759.96
43     69758.98
2     191050.39
47     42559.73
14    132602.65
0     192261.83
Name: Profit, dtype: float64

In [83]:
x_test

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
37  -0.469966       -1.737154        -0.092184          False           False
23  -0.089490       -0.412265         0.540948           True           False
26   0.036937        0.521418        -0.462283           True           False
20   0.051937       -0.214843         0.505076          False           False
29  -0.120740        0.737808        -0.620430          False            True
1    1.452113        0.697565         1.358546          False           False
21   0.086569        0.755842         0.511380          False            True
13   0.307158        0.311235         0.234759          False           False
34  -0.431759        0.851204        -0.011275          False           False
41  -0.732297       -0.924053        -0.283515           True           False
31  -0.193212        0.729778        -0.731614          False            True
33  -0.284711       -0.477784         0.011275           True           False
19   0.216789        0.749534        -1.250030          False            True
24   0.064750       -0.569635        -0.423940          False            True
10   0.468034       -0.294461         0.096638           True           False

In [85]:
y_test

37     89949.14
23    108733.99
26    105733.54
20    118474.03
29    101004.64
1     191792.06
21    111313.02
13    134307.35
34     96712.80
41     77798.83
31     97483.56
33     96778.92
19    122776.86
24    108552.04
10    146121.95
Name: Profit, dtype: float64

In [87]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(x_train, y_train)
model

LinearRegression()

In [89]:
y_pred = lr.predict(x_test)
y_pred

array([ 88469.84073611, 109939.77078424, 110171.95724896, 114918.75384931,
       101862.23258131, 186567.48557092, 117375.45539897, 125487.56787895,
        87279.92227498,  75126.92643588,  97784.99283717,  97928.11353383,
       115466.10291646, 113652.0425858 , 135092.56739517])

In [91]:
train_acc = lr.predict(x_train)


In [93]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.955199699803029

In [95]:
r2_score(y_train, train_acc)

0.9491347776620155

In [98]:
print(sc.transform([[165349.2,136897.80,471784.10]])) #system telling to provide output as the preferred input data

[[1.49673201 0.34535525 1.52241555]]


In [103]:
lr.predict([[1.49673201 ,0.34535525 ,1.52241555,0,1]])

array([192022.86509008])

In [104]:
pickle.dump(lr,open("ML model", mode='wb'))