In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Helly\Desktop\coding\Helly Intern (ML)\7) Machine Learning\2) Classification\1) Logistic Regression\Practical Codes\Social_Network_Ads.csv")
df

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [3]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [4]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# logistic regression

In [7]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [8]:
y_lr = lr.predict(X_test)

# K nearest neighbour

In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [10]:
y_knn = knn.predict(X_test)

# SVC

In [11]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(X_train,y_train)

SVC(kernel='linear')

In [12]:
y_svc = svc.predict(X_test)

In [13]:
from sklearn.svm import SVC
svcr = SVC(kernel='rbf')
svcr.fit(X_train,y_train)

SVC()

In [14]:
y_svcr = svcr.predict(X_test)

# naive bayes

In [15]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,y_train)

GaussianNB()

In [16]:
y_nb = nb.predict(X_test)

# Decision tree

In [17]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion='entropy')
dtc.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [18]:
y_dtc = dtc.predict(X_test)

# random Forest

In [19]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(criterion='entropy', n_estimators=30)
rfc.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [20]:
y_rfc = rfc.predict(X_test)

# evalution

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [22]:
cm_lr = confusion_matrix(y_test,y_lr)
cm_knn = confusion_matrix(y_test,y_knn)
cm_svm = confusion_matrix(y_test,y_svc)
cm_ksvm = confusion_matrix(y_test,y_svcr)
cm_nb = confusion_matrix(y_test,y_nb)
cm_dt = confusion_matrix(y_test,y_dtc)
cm_rf = confusion_matrix(y_test,y_rfc)
print('Logiestic Regression:\n',cm_lr)
print('K_nearest neighbour :\n',cm_knn)
print('SVM :\n',cm_svm)
print('KSVM :\n',cm_ksvm)
print('Naive bayes :\n',cm_nb)
print('Decision tree :\n',cm_dt)
print('random Forest :\n',cm_rf)

Logiestic Regression:
 [[57  1]
 [ 5 17]]
K_nearest neighbour :
 [[55  3]
 [ 1 21]]
SVM :
 [[57  1]
 [ 6 16]]
KSVM :
 [[55  3]
 [ 1 21]]
Naive bayes :
 [[55  3]
 [ 4 18]]
Decision tree :
 [[53  5]
 [ 3 19]]
random Forest :
 [[56  2]
 [ 1 21]]


In [23]:
cm_lr = accuracy_score(y_test,y_lr)
cm_knn = accuracy_score(y_test,y_knn)
cm_svm = accuracy_score(y_test,y_svc)
cm_ksvm = accuracy_score(y_test,y_svcr)
cm_nb = accuracy_score(y_test,y_nb)
cm_dt = accuracy_score(y_test,y_dtc)
cm_rf = accuracy_score(y_test,y_rfc)
print('Logiestic Regression:',cm_lr)
print('K_nearest neighbour :',cm_knn)
print('SVM :',cm_svm)
print('KSVM :',cm_ksvm)
print('Naive bayes :',cm_nb)
print('Decision tree :',cm_dt)
print('random Forest :',cm_rf)

Logiestic Regression: 0.925
K_nearest neighbour : 0.95
SVM : 0.9125
KSVM : 0.95
Naive bayes : 0.9125
Decision tree : 0.9
random Forest : 0.9625
